# .PHONY used to indicate a certain target is not a file
# various marcos or variables
INCULDES = -I
LIBS = -l
CXX = g++
CXXFLAGS = -g -ggdb -std=c++23 -Wall -Wextra -Wsign-conversion -Werror -Wshadow
OBJ = main.o NumericInput.o practice.o
HPP = functions.hpp includes.hpp constants.hpp
# you can use the del or erase keyword
RM = -del

all: main.exe

main.exe: $(OBJ)	
	$(CXX) $(CXXFLAGS) $(OBJ) -o main

main.o: main.cpp $(HPP)
	$(CXX) $(CXXFLAGS) -c main.cpp 

NumericInput.o: NumericInput.cpp $(HPP)
	$(CXX) $(CXXFLAGS) -c NumericInput.cpp 

practice.o: practice.cpp $(HPP)
	$(CXX) $(CXXFLAGS) -c practice.cpp 

.cpp.o:
	$(CXX) $(CXXFLAGS) -c *.cpp

.cpp:
	$(CXX) $(CXXFLAGS) -o $@.cpp *.o

.PHONY : clean

clean:
	$(RM) *.o main.exe
